
# Reference: https://github.com/yasio/yasio/blob/main/.lgtm.yml

extraction: 
  # Define settings for C/C++ analysis
  #####################################
  cpp:
    prepare:
      packages: 
        - gettext
        - libpugixml-dev
        - cmake
        - git
        - make
    # Add an `after-prepare` step if you need to run commands after the prepare step.
    # Each command should be listed on a separate line.
    # This step is useful for C/C++ analysis where you want to prepare the environment
    # for the `configure` step without changing the default behavior for that step. 
    after_prepare:
      - git clone https://github.com/openSUSE/libeconf ./libeconf
      - cd libeconf
      - cmake .
      - make all
      - make DESTDIR=../pre-reqs install || true
      - cd ..
      - git clone https://github.com/PerryWerneck/vmdetect.git ./vmdetect
      - cd vmdetect
      - ./vmdetect/autogen.sh
      - make all
      - sudo make DESTDIR=../pre-reqs install
      - cd ..
      - find ./pre-reqs
      - export LDFLAGS="${LDFLAGS} -L$(readlink -f ./pre-reqs)/usr/local/lib"
      - echo ${LDFLAGS}
      - export ECONF_CFLAGS=""
      - export ECONF_LIBS="-leconf -lm"
      - export VMDETECT_CFLAGS=""
      - export VMDETECT_LIBS="-lvmdetect"

