name: Windows check
on:
  push:
    branches: [ "win", "meson" ]
  pull_request:
    branches: [ "master" ]

jobs:
  MinGW64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Setup MSys
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix xz mingw-w64-x86_64-gcc pkgconf mingw-w64-x86_64-gettext mingw-w64-x86_64-uriparser mingw-w64-x86_64-meson mingw-w64-x86_64-pugixml gettext-devel
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/vmdetect"
          latest: true
          fileName: "mingw-w64-x86_64-vmdetect-1.3.3-0-x86_64.pkg.tar.zst"
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/dmiget"
          latest: true
          fileName: "mingw-w64-x86_64-dmiget-1.2.6-0-x86_64.pkg.tar.zst"
      - name: Run Build
        run: |
          pacman -U --noconfirm *.pkg.tar.zst
          dos2unix PKGBUILD.mingw
          makepkg BUILDDIR=/tmp/pkg -p PKGBUILD.mingw
  